services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=chicken
      - POSTGRES_PASSWORD=chicken
      - POSTGRES_DB=chickendb
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:3000'
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://chicken:chicken@postgres:5432/chickendb

volumes:
  postgres:
